Make modifications needed to build a Python-wrapped version of SHiELD
NOAA-GFDL/SHiELD_build pull request #28
Opened 2023-10-04 16:34 UTC by spencerkclark

**Description**

This PR makes changes required for building a Python wrapped version of SHiELD.  It does two main things:
- It builds all code except the `coupler_main.F90` driver into static libraries, which downstream applications can link to (for now I did this only for the `shield` configuration option, but I could make a similar change for the `solo` configuration as well).
- It adds an option for build all components with position independent code, through adding a `nopic` / `pic` option to the `COMPILE`, `BUILDlibfms`, and `BUILDnceplibs` scripts, and adding an `PIC` option to the Makefile templates for the `gnu`, `intel`, and `nvhpc` compilers.

Fixes #27

**How Has This Been Tested?**

These changes have been tested in ai2cm/SHiELD-wrapper#1.  The continuous integration setup there builds the fortran model and its dependencies using the `COMPILE` script, builds the Python wrapper, and runs several tests.  An important test checks that the Python-wrapped model produces bit-for-bit identical results to the fortran executable for an identically configured run.

**Checklist:**

Please check all whether they apply or not
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-17 17:55 UTC, bensonr approved these changes

2023-10-18 12:15 UTC, laurenchilutti requested changes

2023-10-18 12:15 UTC, laurenchilutti commented on Build/COMPILE
> +          nopic|pic)
Can you initialize pic to a default value? In lines 50-60 you can see that each compile argument is given a default value.

2023-10-18 12:15 UTC, laurenchilutti commented on Build/BUILDlibfms
> +          nopic|pic)
Can you initialize pic to a default value (see lines 27-30)

2023-10-18 12:15 UTC, laurenchilutti commented on Build/BUILDnceplibs
> +          nopic|pic)
Can you initialize pic to a default value (see lines 26-27)

2023-10-18 12:15 UTC, laurenchilutti commented on Build/mk_scripts/MAKE_libFMS
> +        nopic|pic)
Can you initialize PIC to a default value (see lines 31 and 32)

2023-10-18 12:15 UTC, laurenchilutti commented on Build/mk_scripts/mk_make
> +        nopic|pic)
can you initialize PIC (see lines 27-36)

2023-10-18 12:35 UTC, spencerkclark commented
Thanks for the review @laurenchilutti -- good catch.  I added default values for the `pic` argument in all of the relevant scripts.  Let me know if you'd like me to make any more changes.

2023-10-18 13:01 UTC, laurenchilutti approved these changes
Thanks this looks good!

2023-10-18 22:40 UTC, bensonr approved these changes

2023-10-19 11:30 UTC, merged

2023-10-19 12:04 UTC, spencerkclark commented
Thanks @laurenchilutti and @bensonr!